# Generated by Django 4.2 on 2023-05-02 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='counInStock',
            new_name='countInStock',
        ),
    ]
